### PR TITLE
chore: pre-commit hooks

### PR DESCRIPTION
**Pull request by 0xste**
added pre-commit hooks for linting & conventional-commits

### CODE REVIEW

**Review by aaronc — COMMENTED** [review]
Thanks @0xste. Generally looks good. Just curious what's your rationale for this specific set of linters?

**Comment by 0xste** [comment]
@aaronc spotted you folks already used conventional commits + this generally tends to be my standard workflow for go projects. It would be nice to get the CI for tagging semver and publishing tagged versions for this setup too, something i may look at proposing in a subsequent MR 🙏

**Comment by 0xste** [comment]
something like -> https://github.com/marketplace/actions/semver-conventional-commits

**Review by aaronc — APPROVED** [review]
Okay I don't have a strong opinion on linters so fine with merging this.

**Comment by aaronc** [comment]
Thanks for your contribution @0xste

**Pull request merged**
